version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  nodejs:
    build:
      context: .
    container_name: nodejs
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongodb_data:
